Compiler error; consult your Technical Support service
Illegal format of name
Illegal format of literal or invalid use of ALL
Illegal format of character, or name required
Data-name declared twice
Too many data or procedure names declared - compilation abandoned
Illegal character in column 7 or continuation line error
Nested COPY statement or unknown file specified
'.' missing
The statement starts in the wrong area of the source line
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
'DIVISION' missing
'SECTION' missing
'IDENTIFICATION' missing
'PROGRAM-ID' missing
'AUTHOR' missing
'INSTALLATION' missing
'DATE-WRITTEN' missing
'SECURITY' missing
'ENVIRONMENT' missing
'CONFIGURATION' missing
'SOURCE-COMPUTER' missing
OBJECT-COMPUTER or SPECIAL-NAMES clause in error
'OBJECT-COMPUTER' missing
Compiler error; consult your Technical Support service
'SPECIAL-NAMES' missing
SWITCH clause in error
DECIMAL-POINT clause in error
CONSOLE clause in error
Illegal currency symbol
Compiler error; consult your Technical Support service
'DIVISION' missing'
'SECTION' missing
'INPUT-OUTPUT' missing
'FILE-CONTROL' missing
'ASSIGN' missing
'SEQUENTIAL' or 'RELATIVE' or 'INDEXED' missing
'ACCESS' missing on indexed or relative file
'SEQUENTIAL' or 'DYNAMIC' missing
Illegal combination of ORGANIZATION/ACCESS/KEY
Unrecognized clause in SELECT statement
RERUN clause contains syntax error
SAME AREA clause contains syntax error
File-name missing or illegal
'DATA DIVISION' missing
'PROCEDURE DIVISION' missing or unknown statement
'EXCLUSIVE', 'AUTOMATIC' OR 'MANUAL' missing
Non-exclusive lock mode specified for restricted file
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
'DIVISION' missing
'SECTION' missing
File-name not specified in SELECT statement
RECORD SIZE integer missing
Illegal level number or level 01 required
FD qualification contains syntax error
'WORKING-STORAGE' missing
'PROCEDURE DIVISION' missing or unknown statement
Unrecognized clause in data description or previous '.' missing
Incompatible clauses in data description
BLANK is illegal with a non-numeric data-item
PICTURE clause is too long
VALUE with non-elementary item, wrong data-type or value truncated
VALUE clause in error or illegal for PICTURE type
FILLER/SYNC/JUST/BLANK clause for non-elementary item
Preceding item at this level has 0 or more than 8192 bytes
REDEFINES of different levels or unequal field lengths
Data Division exceeds 32k and data item has address above 7FFF
Compiler error; consult your Technical Support service
Data description clause inappropriate or repeated
REDEFINES data-name not declared
USAGE must be COMP, DISPLAY or INDEX
SIGN must be LEADING or TRAILING
SYNCHRONIZED must be LEFT or RIGHT
JUSTIFIED must be RIGHT
BLANK must be ZERO
OCCURS must be numeric, non-zero and unsigned
VALUE must be a literal, numeric literal or figurative constant
PICTURE string has illegal character or illegal precedence
INDEXED data-name missing or already declared
Numeric edited PICTURE string is too large
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Unrecognized verb
IF....ELSE mismatch, or EXIT statement not alone in paragraph
Data-item has wrong data-type or is not declared
Procedure name has been declared twice
Procedure name is the same as a data-name
Name required, or name has been previously mis-declared
Wrong combination of data-types or two USE-procedures on same file
Conditional statement not allowed; imperative statement expected
Malformed subscript, or item not in PROCEDURE DIVISION USING
ACCEPT or DISPLAY wrong
Illegal syntax used with I-O verb
LOCK clause specified for file with lock mode EXCLUSIVE
KEPT specified for uncommittable file
Procedure Division exceeds 32k
KEPT omitted for committable file
IF statements nested too deep (maximum 8)
Structure of Procedure Division wrong (e.g. DECLARATIVES not first)
Reserved word missing or incorrectly used
Too many subscripts in one statement
Too many operands in one statement
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Procedure name has been declared twice (in different segments)
IF....ELSE mismatch at the end of source input
Data-item has wrong data-type or is not declared
Procedure name undeclared
Index-name declared twice
Cursor address field not declared or not 4 bytes long
KEY declaration missing or longer than 32 bytes, or FD missing
STATUS declaration missing
FILE STATUS data-item has the wrong format
Paragraph to be ALTERed is not declared
PROCEDURE DIVISION in error
USING parameter is not declared in the Linkage Section
USING parameter is not level 01 or 77
USING parameter is used twice in the parameter list
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Structure of Procedure Division wrong (eg DECLARATIVES not first)
Compiler error; consult your Technical Support service
Compiler error; consult your Technical Support service
Too many operands in one statement
