Compiler error; consult Technical Support
Illegal format : Data-name 
Illegal format : Literal, or invalid use of 'ALL'
Illegal format : Character
Data-name declared twice
Too many data or procedure names declared - compilation abandoned
Illegal character in column 7 or continuation error
Nested COPY statement or unknown file specified
'.' missing
Wrong A/B area
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
'DIVISION' missing
'SECTION' missing
'IDENTIFICATION' missing
'PROGRAM-ID' missing
'AUTHOR' missing
'INSTALLATION' missing
'DATE-WRITTEN' missing
'SECURITY' missing
'ENVIRONMENT' missing
'CONFIGURATION' missing
'SOURCE-COMPUTER' missing
Error in OBJECT-COMPUTER/SPECIAL-NAMES clause
'OBJECT-COMPUTER' missing
Compiler error; consult Technical Support
'SPECIAL-NAMES' missing
Error in 'SWITCH' clause
Error in 'DECIMAL-POINT' clause
Error in 'CONSOL' clause
Illegal currency symbol
Compiler error; consult Technical Support
'DIVISION' missing'
'SECTION' missing
'INPUT-OUTPUT' missing
'FILE-CONTROL' missing 
'ASSIGN' missing 
'SEQUENTIAL' OR 'RELATIVE' OR 'INDEXED' missing
'ACCESS' missing 
'SEQUENTIAL' OR 'DYNAMIC' missing
Illegal ORGANIZATION/ACCESS/KEY combination
Unrecognized phrase in 'SELECT' clause
Syntax error in 'RERUN' clause
Syntax error in 'SAME AREA' clause
Missing or illegal file-name
'DATA DIVISION' missing
'PROCEDURE DIVISION' missing or unknown stmt
'EXCLUSIVE', 'AUTOMATIC' OR 'MANUAL' missing
Non-exclusive lock mode specified for restricted file
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
'DIVISION' missing
'SECTION' missing
File-name not specified in 'SELECT' stmt
'RECORD SIZE' integer missing
Illegal level number (01-49) or 01 level reqd
Syntax error in 'FD' qualification
'WORKING-STORAGE' missing
'PROCEDURE DIVISION' missing or unknown statement
Data description qualifier or '.' missing
Incompatible 'PICTURE' clause and qualifiers
'BLANK' illegal with non-numeric data
'PICTURE' clause too long
'VALUE' with non-elem item, wrong data-type or value truncated
'VALUE' in error or illegal for 'PICTURE' type
Non-elem item has 'FILLER'/'SYNC'/'JUST'/'BLANK' clause
Preceding item at this level has > 8192 bytes or 0 bytes
'REDEFINES' of unequal fields or different levels
Data storage exceeds 64K, or data item has address above 32k
Compiler error; consult Technical Support
Data description qualifier inappropriate or repeated
'REDEFINES' data-name not declared
'USAGE' must be 'COMP','DISPLAY' OR 'INDEX'
'SIGN' nust be 'LEADING' OR 'TRAILING'
'SYNCHRONIZED' must be 'LEFT' OR 'RIGHT'
'JUSTIFIED' must be 'RIGHT'
'BLANK' must be 'ZERO'
'OCCURS' must be numeric, non-zero and unsigned
'VALUE' must be LITERAL, NUMERIC LITERAL OR FIG CONST
Illegal 'PICTURE' string
'INDEXED' data-name missing or already declared
Numeric-edited PICTURE string is too large
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Unrecognized verb
'IF'....'ELSE' mismatch
Data-item has wrong data-type or is not declared
Procedure name declared twice
Procedure name same as data-name
Name required
Wrong combination of data-types
Conditional statement not allowed in this context
Malformed subscript
'ACCEPT'/'DISPLAY' wrong
Illegal syntax used with I-O verb
'LOCK' clause specified for file with lock mode 'EXCLUSIVE'
'KEPT' specified for uncommittable file
Compiler error; consult Technical Support
'KEPT' omitted for committable file
'IF' statements nested too deep
Incorrect structure of 'PROCEDURE DIVISION'
Reserved word missing or incorrectly used
Too many subscripts in one statement
Too many operands in one statement
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Inter-segment PROCEDURE NAME duplication
'IF'....'ELSE' mismatch
Data-item has wrong data-type or is not declared
Procedure name undeclared
'INDEX' data-name declared twice
Bad cursor control : illegal 'AT' clause
'KEY' declaration missing or FD missing
'STATUS declaration missing
Bad 'STATUS' record
Undefined inter-segment reference or error in ALTER'd para
'PROCEDURE DIVISION' in error
'USING' parameter not declared in 'LINKAGE SECTION'
'USING' parameter not level 01 or 77
'USING' parameter used twice in parameter list
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Incorrect structure of 'PROCEDURE DIVISION'
Compiler error; consult Technical Support
Compiler error; consult Technical Support
Intermediate code buffer overflow
/
