addfun KbdCharIn,		"__KBDCHARIN"	      ,$$USERSCREEN ,0
addfun KbdClose,		"__KBDCLOSE"	      , 	    ,0
addfun KbdDeRegister,		"__KBDDEREGISTER"     , 	    ,0
addfun KbdFlushBuffer,		"__KBDFLUSHBUFFER"    , 	    ,0
addfun KbdFreeFocus,		"__KBDFREEFOCUS"      , 	    ,0
addfun KbdGetCp,		"__KBDGETCP"	      , 	    ,0
addfun KbdGetFocus,		"__KBDGETFOCUS"       , 	    ,0
addfun KbdGetStatus,		"__KBDGETSTATUS"      , 	    ,0
addfun KbdOpen, 		"__KBDOPEN"	      , 	    ,0
addfun KbdPeek, 		"__KBDPEEK"	      , 	    ,0
addfun KbdRegister,		"__KBDREGISTER"       , 	    ,0
addfun KbdSetCp,		"__KBDSETCP"	      , 	    ,0
addfun KbdSetCustXt,		"__KBDSETCUSTXT"      , 	    ,0
;addfun KbdSetFgnd,		 "__KBDSETFGND"       ;Function not supported
addfun KbdSetStatus,		"__KBDSETSTATUS"      , 	    ,0
addfun KbdStringIn,		"__KBDSTRINGIN"       ,$$USERSCREEN ,0
addfun KbdSynch,		"__KBDSYNCH"	      , 	    ,0
addfun KbdXlate,		"__KBDXLATE"	      , 	    ,0
